language: python

python:
  - 3.7
  - 3.8
  - 3.9
  - pypy
  - pypy3

matrix:
  include:
    - python: 3.8
      dist: xenial
  allow_failures:
    - python: pypy3

install:
  - pip install .[dev]

script:
  - inv cover qa

after_success:
  - pip install coveralls
  - coveralls --rcfile=coverage.rc
  - ./travis-bench-after-success.sh
